### ISSUE TITLE
How to use H3LIS331Dl  in 4Wire SPI Mode

### ISSUE THREAD

**Issue by williamesp2015** [Seeed-Studio/Accelerometer_H3LIS331DL#1]
I need to use H3LIS331 by SPI mode. I know the SPI Mode is 3 .

**Comment by lanselambor** [comment]
@williamesp2015 What a pity, this grove module only provides I2C interface on the board. I found sparkfun also has this module and has SPI interface.

https://github.com/sparkfun/SparkFun_LIS331_Arduino_Library
