### ISSUE TITLE
add to Arduino Library Manager

### ISSUE THREAD

**Issue by chrislevey** [Seeed-Studio/Accelerometer_H3LIS331DL#3]
Could you now add to the Arduino Library manager?  See:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
Thanks.

**Comment by lanselambor** [comment]
Please check it in Arduino Library Manager.  Search Accelerometer_H3LIS331DL, ![image](https://user-images.githubusercontent.com/9337688/45661449-2cd85700-bb30-11e8-95cc-dd4b644e34b5.png)

**Comment by chrislevey** [comment]
Thanks - now shows up in manager, but gives error..
I think your
#include “arduino.h”
should be with an A rather than a, like this:
#include “Arduino.h”

See enclosed screenshot error:

[cid:8389DA4C-F144-409A-A76E-93B87DB79903@Home]

On Sep 17,2018, at 10:48 PM, Lambor <notifications@github.com<mailto:notifications@github.com>> wrote:


Please check the repo in Arduino Library Manager. Search Accelerometer_H3LIS331DL,[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F9337688%2F45661449-2cd85700-bb30-11e8-95cc-dd4b644e34b5.png&data=02%7C01%7Cchristopher.g.levey%40dartmouth.edu%7Cfdb50045c84b4c4b6dcc08d61d112851%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C636728356865002179&sdata=otZ7FCdez1paDRtDumNmQhCXYzeOttllUHYxF9Oir4g%3D&reserved=0>

**Comment by KillingJacky** [comment]
Fixed in https://github.com/Seeed-Studio/Accelerometer_H3LIS331DL/releases/tag/v1.0.2 Will be available in Arduino IDE's library manager in library manager's next pull.
